version: 2
jobs:
  build:
    docker:
      - image: node:7.10.0
    working_directory: ~/react-playground
    steps:
      - checkout
      - add_ssh_keys
      - run: |
          yarn
      - run: |
          yarn run test
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]
          then
            git config --global user.name "Circle CI" && git config --global user.email "circleci@example.com" && yarn run deploy
          else
            yarn run build
            echo 'Not master branch, therefore not deploying ^_^'
          fi